# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  setPreference: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 144000 #40 hrs
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  requireAdminNotify: true
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  - Paramedic # Hardlight: Add Paramedic access
  special:
  # - !type:AddImplantSpecial
    # implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      SpeedModifier: 2.5
    - type: CommandStaff
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  # Shitmed Change

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash
